# Generated by Django 5.0.11 on 2025-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('DRA', 'Drama'), ('COM', 'Comedy'), ('ACT', 'Action'), ('WAR', 'War'), ('THR', 'Thriller'), ('HOR', 'Horror'), ('SCF', 'Sci-Fi'), ('FAN', 'Fantasy'), ('ANI', 'Animation'), ('ADV', 'Adventure'), ('DOC', 'Documentary'), ('WED', 'Western'), ('MUS', 'Music'), ('SYF', 'Sci-Fi'), ('ROM', 'Romance'), ('HIS', 'History'), ('ART', 'Art'), ('POL', 'Political'), ('CRI', 'Crime')], max_length=100, null=True),
        ),
    ]
